# Generated by Django 5.2.17 on 2026-09-15 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('atencion', models.CharField(max_length=100)),
                ('subatencion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('solicitud_problema', models.TextField()),
                ('accion', models.TextField()),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ambito', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('dias_computables', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('umbral_ambar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umbral_colectivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('version_parametros', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/')),
                ('fecha', models.DateField()),
                ('metadatos', models.TextField(blank=True)),
                ('estado_revision', models.CharField(default='pendiente', max_length=30)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='core.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_institucional', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='core.cargo')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='core.delegacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.periodo'),
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True)),
                ('resultado', models.BooleanField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('evidencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validacion', to='core.evidencia')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_realizadas', to='core.funcionario')),
            ],
        ),
    ]
