# Generated by Django 5.2.17 on 2026-09-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('computable_days', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=30)),
                ('amber_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collective_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parameters_version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('attention', models.CharField(max_length=100)),
                ('sub_attention', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('request_description', models.TextField()),
                ('action_taken', models.TextField()),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='organization.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='performance.period')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/')),
                ('date', models.DateField()),
                ('metadata', models.TextField(blank=True)),
                ('review_status', models.CharField(default='pendiente', max_length=30)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='performance.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('result', models.BooleanField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations_performed', to='organization.employee')),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='performance.evidence')),
            ],
        ),
    ]
