# Generated by Django 5.2.17 on 2026-09-28 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('performance', '0004_finalize_activity_attention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='performance.period')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='organization.position')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='performance.meta'),
        ),
    ]
