# Generated by Django 5.2.17 on 2026-09-28 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('performance', '0005_meta_activity_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=150)),
                ('requester', models.CharField(max_length=150)),
                ('territory', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('support_area', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ingresado', 'Ingresado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('realizado', 'Realizado')], default='ingresado', max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='organization.delegation')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='organization.employee')),
            ],
        ),
    ]
