# Generated by Django 5.2.17 on 2026-09-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Si tiene fecha, el registro está eliminado (borrado lógico).', null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Si tiene fecha, el registro está eliminado (borrado lógico).', null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Si tiene fecha, el registro está eliminado (borrado lógico).', null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Si tiene fecha, el registro está eliminado (borrado lógico).', null=True),
        ),
    ]
