# Generated by Django 5.2.17 on 2026-10-02 14:52

import performance.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_evidence_code_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_taken',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='request_description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='observation',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to='evidence/%Y/%m/', validators=[performance.validators.validate_evidence_file]),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='metadata',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='validation',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
