"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = env('SECRET_KEY')

DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'organization',
    'performance',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': BASE_DIR / env('DB_NAME', default='db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Largo mínimo 10 (rúbrica formativa req. 4). Es MinimumLengthValidator
        # de Django con el mensaje en español; ver accounts/validators.py.
        'NAME': 'accounts.validators.SpanishMinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        # Mayúscula + minúscula + número + carácter especial (Fase 4, rúbrica
        # formativa req. 4). Ver accounts/validators.py.
        'NAME': 'accounts.validators.PasswordComplexityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Chile (Fase 6, patch 13, Decisión 27). Con 'UTC', desde las 20:00-21:00 de
# Chile `timezone.localdate()` ya devolvía la fecha de mañana y las reglas de
# fecha de los formularios rechazaban "hoy". Con USE_TZ activo la base sigue
# guardando UTC, así que este cambio no requiere migración de datos.
TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Autenticación (Fase 4). Las vistas protegidas con @login_required /
# LoginRequiredMixin redirigen acá; tras entrar se va a la portada del CRUD
# web (Fase 6, patch 13, Decisión 27), igual para todos los roles.
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'performance:home'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Email de desarrollo (Fase 3, Ing. Software): en vez de enviar correos
# reales, los imprime en la consola/log del servidor. No requiere SMTP,
# cuenta de Gmail ni correo real -- es lo que el profesor pidió: el código
# de recuperación debe "llegar" por correo, no mostrarse en pantalla.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'sgr-noreply@municipalidadlaserena.cl'


# Headers de seguridad adicionales (Ing. Software, mitigación OWASP A05).
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True


# API REST (Evaluación Sumativa 3): Django REST Framework + Simple JWT.
# - Autenticación: SOLO JWT (`Authorization: Bearer <access>`). No se agrega
#   SessionAuthentication a propósito: con ella, una solicitud sin token
#   recibiría 403 en vez de 401.
# - Permiso por defecto: ApiRolePermission (api/permissions.py). Falla cerrado:
#   toda vista nueva queda protegida por rol salvo que declare otra cosa (los
#   endpoints de token de Simple JWT son públicos por definición).
# - Renderer solo JSON: no se expone el navegador HTML de DRF.
# - Paginación: 25 por página; otra página se pide con ?page=N.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'api.permissions.ApiRolePermission',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}

# Simple JWT. Los tokens se firman con SECRET_KEY (HS256): usar una de 32 o más
# caracteres (la que genera Django tiene 50). Las duraciones se pueden cambiar
# en el .env; si faltan, se usan estos valores por defecto.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env.int('JWT_ACCESS_MINUTES', default=30)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env.int('JWT_REFRESH_DAYS', default=1)),
    'AUTH_HEADER_TYPES': ('Bearer',),
}
